export const dummyJobs = [
    {
      id: "1",
      title: "Senior Frontend Developer",
      company: "TechCorp Solutions",
      location: "San Francisco, CA",
      category: "Technology",
      experienceLevel: "Senior",
      type: "Full-time",
      salary: "$120,000 - $160,000",
      description:
        "We are looking for a Senior Frontend Developer to join our dynamic team. You will be responsible for developing user-facing features using modern JavaScript frameworks and ensuring optimal user experience.",
      requirements: [
        "5+ years of React experience",
        "Strong TypeScript knowledge",
        "Experience with modern CSS frameworks",
        "Knowledge of testing frameworks",
        "Git version control proficiency",
      ],
      benefits: [
        "Health, dental, and vision insurance",
        "Flexible work hours",
        "Remote work options",
        "401(k) matching",
        "Professional development budget",
      ],
      postedDate: "2024-01-15",
      applicationDeadline: "2024-02-15",
    },
    {
      id: "2",
      title: "Digital Marketing Specialist",
      company: "Creative Agency Pro",
      location: "New York, NY",
      category: "Marketing",
      experienceLevel: "Mid-Level",
      type: "Full-time",
      salary: "$65,000 - $85,000",
      description:
        "Join our creative team as a Digital Marketing Specialist. You will develop and execute comprehensive digital marketing campaigns across various platforms to drive brand awareness and customer engagement.",
      requirements: [
        "3-5 years of digital marketing experience",
        "Google Ads and Analytics certification",
        "Social media marketing expertise",
        "Content creation skills",
        "SEO/SEM knowledge",
      ],
      benefits: [
        "Creative work environment",
        "Professional development opportunities",
        "Health insurance",
        "Flexible PTO",
        "Team building events",
      ],
      postedDate: "2024-01-12",
      applicationDeadline: "2024-02-12",
    },
    {
      id: "3",
      title: "Junior Data Analyst",
      company: "DataViz Inc",
      location: "Austin, TX",
      category: "Data Science",
      experienceLevel: "Entry-Level",
      type: "Full-time",
      salary: "$55,000 - $70,000",
      description:
        "Entry-level position perfect for recent graduates or career changers. You will work with our data team to analyze trends, create visualizations, and support data-driven decision making.",
      requirements: [
        "Bachelor's degree in related field",
        "SQL knowledge",
        "Experience with Excel or Google Sheets",
        "Basic Python or R knowledge preferred",
        "Strong analytical thinking",
      ],
      benefits: [
        "Mentorship program",
        "Learning and development stipend",
        "Health insurance",
        "Casual work environment",
        "Growth opportunities",
      ],
      postedDate: "2024-01-10",
      applicationDeadline: "2024-02-10",
    },
    {
      id: "4",
      title: "UX/UI Designer",
      company: "Design Studio Elite",
      location: "Los Angeles, CA",
      category: "Design",
      experienceLevel: "Mid-Level",
      type: "Full-time",
      salary: "$75,000 - $95,000",
      description:
        "We are seeking a talented UX/UI Designer to create intuitive and visually appealing user interfaces. You will collaborate with cross-functional teams to deliver exceptional user experiences.",
      requirements: [
        "3-4 years of UX/UI design experience",
        "Proficiency in Figma or Sketch",
        "Understanding of user-centered design principles",
        "Portfolio showcasing design projects",
        "Collaboration and communication skills",
      ],
      benefits: [
        "Creative freedom",
        "Latest design tools and equipment",
        "Health and dental insurance",
        "Professional development budget",
        "Flexible work arrangements",
      ],
      postedDate: "2024-01-08",
      applicationDeadline: "2024-02-08",
    },
    {
      id: "5",
      title: "Project Manager",
      company: "Global Ventures Ltd",
      location: "Chicago, IL",
      category: "Management",
      experienceLevel: "Senior",
      type: "Full-time",
      salary: "$95,000 - $125,000",
      description:
        "Lead and manage complex projects from initiation to completion. You will coordinate with various stakeholders, ensure project delivery within scope and budget, and drive continuous improvement initiatives.",
      requirements: [
        "PMP certification preferred",
        "5+ years of project management experience",
        "Agile/Scrum methodology knowledge",
        "Strong leadership and communication skills",
        "Experience with project management tools",
      ],
      benefits: [
        "Leadership development programs",
        "Comprehensive health benefits",
        "Performance bonuses",
        "Flexible work schedule",
        "Professional certification support",
      ],
      postedDate: "2024-01-05",
      applicationDeadline: "2024-02-05",
    },
    {
      id: "6",
      title: "Content Writer",
      company: "Content Creators Hub",
      location: "Remote",
      category: "Content",
      experienceLevel: "Entry-Level",
      type: "Remote",
      salary: "$45,000 - $60,000",
      description:
        "Create engaging content for various digital platforms. You will research topics, write articles, blog posts, and marketing copy while maintaining brand voice and SEO best practices.",
      requirements: [
        "Excellent writing and editing skills",
        "SEO knowledge",
        "Research abilities",
        "Social media familiarity",
        "Ability to meet deadlines",
      ],
      benefits: [
        "Fully remote position",
        "Flexible work hours",
        "Professional writing tools",
        "Health insurance stipend",
        "Career growth opportunities",
      ],
      postedDate: "2024-01-03",
      applicationDeadline: "2024-02-03",
    },
    {
      id: "7",
      title: "DevOps Engineer",
      company: "CloudTech Systems",
      location: "Seattle, WA",
      category: "Technology",
      experienceLevel: "Mid-Level",
      type: "Full-time",
      salary: "$90,000 - $120,000",
      description:
        "Join our infrastructure team to build and maintain scalable cloud solutions. You will work with containerization, CI/CD pipelines, and automation tools to ensure reliable software delivery.",
      requirements: [
        "3-5 years of DevOps experience",
        "AWS/Azure/GCP knowledge",
        "Docker and Kubernetes experience",
        "CI/CD pipeline expertise",
        "Infrastructure as Code (IaC) skills",
      ],
      benefits: [
        "Cloud certification support",
        "Latest technology stack",
        "Health and wellness benefits",
        "Stock options",
        "Remote work flexibility",
      ],
      postedDate: "2024-01-01",
      applicationDeadline: "2024-02-01",
    },
    {
      id: "8",
      title: "Sales Representative",
      company: "SalesForce Pro",
      location: "Miami, FL",
      category: "Sales",
      experienceLevel: "Entry-Level",
      type: "Full-time",
      salary: "$50,000 - $70,000 + Commission",
      description:
        "Launch your sales career with our dynamic team. You will identify prospects, build relationships, and close deals while receiving comprehensive training and mentorship.",
      requirements: [
        "Bachelor's degree preferred",
        "Strong communication skills",
        "Goal-oriented mindset",
        "CRM software familiarity",
        "Willingness to learn and adapt",
      ],
      benefits: [
        "Uncapped commission potential",
        "Comprehensive sales training",
        "Health benefits",
        "Career advancement opportunities",
        "Team incentives and rewards",
      ],
      postedDate: "2023-12-28",
      applicationDeadline: "2024-01-28",
    },
  ];