export const dummyJobs = [
  {
    _id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Solutions",
    description: "We are looking for a Senior Frontend Developer to join our dynamic team. You will be responsible for developing user-facing features using modern JavaScript frameworks and ensuring optimal user experience.",
    requirements: [
      "5+ years of React experience",
      "Strong TypeScript knowledge",
      "Experience with modern CSS frameworks",
      "Knowledge of testing frameworks",
      "Git version control proficiency",
    ],
    responsibilities: [
      "Develop and maintain high-quality user interfaces",
      "Collaborate with designers and backend developers",
      "Write clean, maintainable, and well-documented code",
      "Participate in code reviews and technical discussions",
      "Mentor junior developers and share knowledge"
    ],
    benefits: [
      "Health, dental, and vision insurance",
      "Flexible work hours",
      "Remote work options",
      "401(k) matching",
      "Professional development budget",
    ],
    jobType: "Full-time",
    category: "Technology",
    region: "San Francisco",
    country: "USA",
    salary: 120000,
    experience: "5+ years",
    education: "Bachelor's degree in Computer Science or related field",
    createdAt: "2024-01-15T10:00:00Z",
    companyDescription: "TechCorp Solutions is a leading technology company specializing in innovative software solutions for businesses worldwide.",
    companySize: "100-500 employees",
    companyWebsite: "https://techcorp-solutions.com",
    companyEmail: "careers@techcorp-solutions.com",
    companyPhone: "+1 (555) 123-4567"
  },
  {
    _id: "2",
    title: "Digital Marketing Specialist",
    company: "Creative Agency Pro",
    description: "Join our creative team as a Digital Marketing Specialist. You will develop and execute comprehensive digital marketing campaigns across various platforms to drive brand awareness and customer engagement.",
    requirements: [
      "3-5 years of digital marketing experience",
      "Google Ads and Analytics certification",
      "Social media marketing expertise",
      "Content creation skills",
      "SEO/SEM knowledge",
    ],
    responsibilities: [
      "Develop and execute digital marketing strategies",
      "Manage social media accounts and campaigns",
      "Create engaging content for various platforms",
      "Analyze campaign performance and optimize results",
      "Collaborate with creative and design teams"
    ],
    benefits: [
      "Creative work environment",
      "Professional development opportunities",
      "Health insurance",
      "Flexible PTO",
      "Team building events",
    ],
    jobType: "Full-time",
    category: "Marketing",
    region: "New York",
    country: "USA",
    salary: 75000,
    experience: "3-5 years",
    education: "Bachelor's degree in Marketing or related field",
    createdAt: "2024-01-12T10:00:00Z",
    companyDescription: "Creative Agency Pro is a full-service marketing agency that helps brands connect with their audiences through innovative campaigns.",
    companySize: "50-100 employees",
    companyWebsite: "https://creativeagencypro.com",
    companyEmail: "careers@creativeagencypro.com",
    companyPhone: "+1 (555) 234-5678"
  },
  {
    _id: "3",
    title: "Junior Data Analyst",
    company: "DataViz Inc",
    description: "Entry-level position perfect for recent graduates or career changers. You will work with our data team to analyze trends, create visualizations, and support data-driven decision making.",
    requirements: [
      "Bachelor's degree in related field",
      "SQL knowledge",
      "Experience with Excel or Google Sheets",
      "Basic Python or R knowledge preferred",
      "Strong analytical thinking",
    ],
    responsibilities: [
      "Collect and clean data from various sources",
      "Create data visualizations and reports",
      "Perform statistical analysis and modeling",
      "Support business decision-making with data insights",
      "Collaborate with cross-functional teams"
    ],
    benefits: [
      "Mentorship program",
      "Learning and development stipend",
      "Health insurance",
      "Casual work environment",
      "Growth opportunities",
    ],
    jobType: "Full-time",
    category: "Data Science",
    region: "Austin",
    country: "USA",
    salary: 62500,
    experience: "Entry Level",
    education: "Bachelor's degree in Statistics, Mathematics, or related field",
    createdAt: "2024-01-10T10:00:00Z",
    companyDescription: "DataViz Inc specializes in transforming complex data into actionable insights through advanced analytics and visualization.",
    companySize: "25-50 employees",
    companyWebsite: "https://dataviz-inc.com",
    companyEmail: "careers@dataviz-inc.com",
    companyPhone: "+1 (555) 345-6789"
  },
  {
    _id: "4",
    title: "UX/UI Designer",
    company: "Design Studio Elite",
    description: "We are seeking a talented UX/UI Designer to create intuitive and visually appealing user interfaces. You will collaborate with cross-functional teams to deliver exceptional user experiences.",
    requirements: [
      "3-4 years of UX/UI design experience",
      "Proficiency in Figma or Sketch",
      "Understanding of user-centered design principles",
      "Portfolio showcasing design projects",
      "Collaboration and communication skills",
    ],
    responsibilities: [
      "Create user-centered design solutions",
      "Design wireframes, prototypes, and high-fidelity mockups",
      "Conduct user research and usability testing",
      "Collaborate with product managers and developers",
      "Maintain design system and component library"
    ],
    benefits: [
      "Creative freedom",
      "Latest design tools and equipment",
      "Health and dental insurance",
      "Professional development budget",
      "Flexible work arrangements",
    ],
    jobType: "Full-time",
    category: "Design",
    region: "Los Angeles",
    country: "USA",
    salary: 85000,
    experience: "3-4 years",
    education: "Bachelor's degree in Design or related field",
    createdAt: "2024-01-08T10:00:00Z",
    companyDescription: "Design Studio Elite creates exceptional digital experiences through innovative design thinking and creative solutions.",
    companySize: "25-50 employees",
    companyWebsite: "https://designstudioelite.com",
    companyEmail: "careers@designstudioelite.com",
    companyPhone: "+1 (555) 456-7890"
  },
  {
    _id: "5",
    title: "Project Manager",
    company: "Global Ventures Ltd",
    description: "Lead and manage complex projects from initiation to completion. You will coordinate with various stakeholders, ensure project delivery within scope and budget, and drive continuous improvement initiatives.",
    requirements: [
      "PMP certification preferred",
      "5+ years of project management experience",
      "Agile/Scrum methodology knowledge",
      "Strong leadership and communication skills",
      "Experience with project management tools",
    ],
    responsibilities: [
      "Plan and execute project activities",
      "Manage project scope, timeline, and budget",
      "Lead cross-functional project teams",
      "Identify and mitigate project risks",
      "Communicate project status to stakeholders"
    ],
    benefits: [
      "Leadership development programs",
      "Comprehensive health benefits",
      "Performance bonuses",
      "Flexible work schedule",
      "Professional certification support",
    ],
    jobType: "Full-time",
    category: "Management",
    region: "Chicago",
    country: "USA",
    salary: 110000,
    experience: "5+ years",
    education: "Bachelor's degree in Business or related field",
    createdAt: "2024-01-05T10:00:00Z",
    companyDescription: "Global Ventures Ltd is a multinational company specializing in strategic consulting and project management services.",
    companySize: "500+ employees",
    companyWebsite: "https://globalventures.com",
    companyEmail: "careers@globalventures.com",
    companyPhone: "+1 (555) 567-8901"
  },
  {
    _id: "6",
    title: "Content Writer",
    company: "Content Creators Hub",
    description: "Create engaging content for various digital platforms. You will research topics, write articles, blog posts, and marketing copy while maintaining brand voice and SEO best practices.",
    requirements: [
      "Excellent writing and editing skills",
      "SEO knowledge",
      "Research abilities",
      "Social media familiarity",
      "Ability to meet deadlines",
    ],
    responsibilities: [
      "Write engaging content for various platforms",
      "Research industry trends and topics",
      "Optimize content for SEO",
      "Collaborate with marketing and design teams",
      "Maintain consistent brand voice and style"
    ],
    benefits: [
      "Fully remote position",
      "Flexible work hours",
      "Professional writing tools",
      "Health insurance stipend",
      "Career growth opportunities",
    ],
    jobType: "Remote",
    category: "Content",
    region: "Remote",
    country: "USA",
    salary: 52500,
    experience: "Entry Level",
    education: "Bachelor's degree in English, Journalism, or related field",
    createdAt: "2024-01-03T10:00:00Z",
    companyDescription: "Content Creators Hub is a digital content agency that helps brands tell their stories through compelling written content.",
    companySize: "10-25 employees",
    companyWebsite: "https://contentcreatorshub.com",
    companyEmail: "careers@contentcreatorshub.com",
    companyPhone: "+1 (555) 678-9012"
  },
  {
    _id: "7",
    title: "DevOps Engineer",
    company: "CloudTech Systems",
    description: "Join our infrastructure team to build and maintain scalable cloud solutions. You will work with containerization, CI/CD pipelines, and automation tools to ensure reliable software delivery.",
    requirements: [
      "3-5 years of DevOps experience",
      "AWS/Azure/GCP knowledge",
      "Docker and Kubernetes experience",
      "CI/CD pipeline expertise",
      "Infrastructure as Code (IaC) skills",
    ],
    responsibilities: [
      "Design and implement cloud infrastructure",
      "Automate deployment and scaling processes",
      "Monitor system performance and reliability",
      "Implement security best practices",
      "Collaborate with development teams"
    ],
    benefits: [
      "Cloud certification support",
      "Latest technology stack",
      "Health and wellness benefits",
      "Stock options",
      "Remote work flexibility",
    ],
    jobType: "Full-time",
    category: "Technology",
    region: "Seattle",
    country: "USA",
    salary: 105000,
    experience: "3-5 years",
    education: "Bachelor's degree in Computer Science or related field",
    createdAt: "2024-01-01T10:00:00Z",
    companyDescription: "CloudTech Systems provides cutting-edge cloud infrastructure and DevOps solutions for enterprise clients.",
    companySize: "100-250 employees",
    companyWebsite: "https://cloudtechsystems.com",
    companyEmail: "careers@cloudtechsystems.com",
    companyPhone: "+1 (555) 789-0123"
  },
  {
    _id: "8",
    title: "Sales Representative",
    company: "SalesForce Pro",
    description: "Launch your sales career with our dynamic team. You will identify prospects, build relationships, and close deals while receiving comprehensive training and mentorship.",
    requirements: [
      "Bachelor's degree preferred",
      "Strong communication skills",
      "Goal-oriented mindset",
      "CRM software familiarity",
      "Willingness to learn and adapt",
    ],
    responsibilities: [
      "Identify and qualify sales prospects",
      "Build and maintain customer relationships",
      "Present product solutions to clients",
      "Negotiate contracts and close deals",
      "Meet and exceed sales targets"
    ],
    benefits: [
      "Uncapped commission potential",
      "Comprehensive sales training",
      "Health benefits",
      "Career advancement opportunities",
      "Team incentives and rewards",
    ],
    jobType: "Full-time",
    category: "Sales",
    region: "Miami",
    country: "USA",
    salary: 60000,
    experience: "Entry Level",
    education: "Bachelor's degree preferred",
    createdAt: "2023-12-28T10:00:00Z",
    companyDescription: "SalesForce Pro is a leading sales training and consulting company that helps organizations improve their sales performance.",
    companySize: "50-100 employees",
    companyWebsite: "https://salesforcepro.com",
    companyEmail: "careers@salesforcepro.com",
    companyPhone: "+1 (555) 890-1234"
  },
];